### ISSUE TITLE
atualizar o readme

### ISSUE THREAD

**Issue by bruno3du** [gkpiccoli/webProject#1]
Como recomendações é possível adicionar imagens, mais detalhes do projeto, o que você aprendeu com ele, quais foram as dificuldades, adicionar badges e ser criativo para adicionar mais do seu estilo.

**Comment by gkpiccoli** [comment]
Obrigado por ler meu código e pelo feedback @bruno3du! Vou me atentar nisso no meu próximo projeto, espero que fique melhor. Sucesso!
